### PR TITLE
add "empty" variable only when needed (resolving compile warnings)

### PR DESCRIPTION
**Pull request by michael72**
use "exists" rather than "any" as "any" is a nim keyword
fix wrong elif-tree in inlineFilter

### CODE REVIEW

**Comment by alehander42** [comment]
Hey, thank you! Will take a look later. However I test most of my stuff on
relatively newer devel indeed, what version do you us

**Comment by alehander42** [comment]
Great work!

However it seems that current zero-functional of filter is working fine with Nim devel (a compiler built from the devel branch of Nim), probably there are some internal changes leading to need for different implementations.

What version of Nim are you using? Eventually we can mantain this older Nim version with some when checks, but I have to know which Nim to test with.

Also, any isn't a keyword currently (https://nim-lang.org/docs/manual.html#lexical-analysis-identifiers-keywords)

**Comment by michael72** [comment]
OK - any does not seem to be a keyword, but it is recognized as a type - at least the syntax highlighting both with vs-code and also here on github looks different for 'any' as compared to the other used names (all, etc.)

The versions I used is the latest release (0.17.2) and the devel branch I compiled today. Both give me positive results on the provided tests with my code changes.
(btw using ! for identifiers is now deprecated - so that is new...)

Using the new devel branch I also get with 'nim c test.c' the following errors:
```
test.nim(16, 7) template/generic instantiation from here
test.nim(56, 8) template/generic instantiation from here
test.nim(57, 23) template/generic instantiation from here
zero_functional.nim(102, 10) Error: illformed AST:
elif it1 mod 4 > 1:
  var it2 = it1
```

that is because you used the elif-brach rather than the statement-list in the branch returned from the filter... (still I really struggled with this strange error message at first).

So - i am going to check in my own update - but not sure whether to post a pull-request... I did some rework and added "index" and "foreach" functions. Maybe you can have a look if you're interested.

**Comment by michael72** [comment]
OK - any does not seem to be a keyword, but it is recognized as a type - at least the syntax highlighting both with vs-code and also here on github looks different for 'any' as compared to the other used names (all, etc.)

The versions I used is the latest release (0.17.2) and the devel branch I compiled today. Both give me positive results on the provided tests with my code changes.
(btw using ! for identifiers is now deprecated - so that is new...)

Using the new devel branch I also get with 'nim c test.c' the following errors:
```
test.nim(16, 7) template/generic instantiation from here
test.nim(56, 8) template/generic instantiation from here
test.nim(57, 23) template/generic instantiation from here
zero_functional.nim(102, 10) Error: illformed AST:
elif it1 mod 4 > 1:
  var it2 = it1
```

that is because you used the elif-brach rather than the statement-list in the branch returned from the filter... (still I really struggled with this strange error message at first).

So - i am going to check in my own update - but not sure whether to post a pull-request... I did some rework and added "index" and "foreach" functions. Maybe you can have a look if you're interested.

**Comment by alehander42** [comment]
The problem is, I am sure it works with the devel branch, as the travis config also build always the last devel and you can see it passes this test with it (also on my local machine).

Is it possible that you somehow have older version of the stdlib in your nim path? On which OS are you? I'll try now with 17.2

**Comment by michael72** [comment]
That is weird - I'm on Windows 10
I do not have an old version of the stdlib - at least I don't know how that is possible...

Could you check what is your output in inlineFilter - as suggested in my comment - just echo(treeRepr(q))
Is there a StmtList under your ElifBranch?

```nim
 #[
        check with echo(treeRepr(q))

        StmtList (q)
            IfStmt (q[0])
                ElifBranch (q[0][0])
                    <<Conditition>>
                    StmtList (q[0][0][1])
                        <<LetSection>>..
    ]#
```
... and could you also check if you get errors in your test when you change linlineFilter to return (q, q[0][0][1])  - or q[0][0][^1] if you prefer that?

**Pull request merged**
